# directory or S3 bucket + prefix where notebook report templates 
# are stored.  Specify an S3 bucket and prefix by:  s3://bucket/prefix-to-templates
template_path: 

# directory or S3 bucket + prefix where created reports are stored.
output_path: 

# a list or iterable containing the base BMON Server URLs that should be 
# processed for creating reports.  e.g. ['https://bms.ahfc.us', 'https://bmon.analysisnorth.com']
bmon_urls: 
  - https://bms.ahfc.us
  - https://bmon.analysisnorth.com

# directory or S3 bucket + prefix to store log files from report
# creation; defaults to 'bmon-report-logs' in current directory
# if this entry is not present.
# log_file_path: 
