# These are the GitHub repositories that are looped through to determine the BMON
# servers to scan and the Jupyter Notebook reports to run.  Each GitHub repo contains
# the Jupyter Notebook templates that produce the energy reports and contain a
# configuration file that determines what BMON servers to apply the reports to.
source_repos:
  - url: https://bms.afc.us
  - url: https://bmon.analysisnorth.com
  - url: https://bmon.analysisnorth.com
    branch: revised

# logging level: DEBUG, INFO, WARNING, ERROR
log_level:  INFO

# The number of cores available for processing this script.  Allocating more cores
# will increase processing speed.
cores: 2
